/**
 * `slowcook dev-env init` — scaffold `.brewing/dev-env.yaml` from
 * detected apps in the consumer's repo. Phase 2.1 of the dev-env arc.
 *
 * Detection heuristics (lightweight, no actual build):
 *   - Walks `apps/*` looking for sub-dirs with a package.json.
 *   - Infers `mode` from dependencies:
 *       Next.js  → mode: dev (hot-reload-friendly)
 *       NestJS   → mode: nest-watch
 *       fallback → mode: start
 *   - Assigns sequential ports starting at 3000.
 *   - Sets reasonable defaults for source_branch, persistence.
 *   - Leaves ssh_target empty (consumer fills in).
 *
 * The output is a STARTING POINT — consumers tweak ports, container
 * names, ssh_target details by hand. `init --force` overwrites; the
 * default refuses to clobber an existing file.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import YAML from "yaml";

interface DetectedApp {
  name: string;
  mode: "dev" | "start" | "nest-watch";
  port: number;
}

interface InitArgs {
  repoRoot: string;
  force: boolean;
  appsDir: string;
}

function parseArgs(argv: string[]): InitArgs {
  const args: InitArgs = {
    repoRoot: process.cwd(),
    force: false,
    appsDir: "apps",
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = argv[i + 1];
    if (a === "--cwd" && next) {
      args.repoRoot = next;
      i++;
    } else if (a === "--apps-dir" && next) {
      args.appsDir = next;
      i++;
    } else if (a === "--force") {
      args.force = true;
    }
  }
  return args;
}

export function detectAppsForInit(
  repoRoot: string,
  appsDir = "apps",
): DetectedApp[] {
  const root = join(repoRoot, appsDir);
  if (!existsSync(root)) return [];
  const out: DetectedApp[] = [];
  let port = 3000;
  for (const name of readdirSync(root).sort()) {
    const appDir = join(root, name);
    if (!statSync(appDir).isDirectory()) continue;
    const pkgPath = join(appDir, "package.json");
    if (!existsSync(pkgPath)) continue;
    let pkg: { dependencies?: Record<string, string>; devDependencies?: Record<string, string> } = {};
    try {
      pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    } catch {
      continue;
    }
    const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
    let mode: DetectedApp["mode"] = "start";
    if (deps["next"]) mode = "dev";
    else if (deps["@nestjs/core"] || deps["@nestjs/common"]) mode = "nest-watch";
    out.push({ name, mode, port: port++ });
  }
  return out;
}

export function renderDevEnvYaml(apps: DetectedApp[]): string {
  const yaml = {
    $schema: "./dev-env.schema.json",
    schema_version: 1,
    source_branch: "dev",
    seed_script: "scripts/seed-dev-data.ts",
    ssh_target: {
      host: "REPLACE_ME.example.com",
      user: "deploy",
      checkout_dir: "/opt/yourapp-dev",
      key_secret: "YOURAPP_DEV_SSH_KEY",
    },
    persistence: {
      db_volume: "pg-dev-data",
      uploads_volume: "",
    },
    apps: Object.fromEntries(
      apps.map((a) => [
        a.name,
        {
          mode: a.mode,
          port: a.port,
          container: a.name,
        },
      ]),
    ),
  };
  return (
    `# slowcook dev-env config — generated by \`slowcook dev-env init\`.\n` +
    `# Hand-tweak: ssh_target.{host,user,checkout_dir,key_secret} must point at\n` +
    `# YOUR deploy box; ports may collide on a small host — adjust to free ones;\n` +
    `# container names default to app names — change if your compose uses others.\n` +
    `#\n` +
    `# See packages/cli/src/commands/dev-env/config.ts in slowcook for the\n` +
    `# full zod schema.\n\n` +
    YAML.stringify(yaml, { lineWidth: 0 })
  );
}

export async function devEnvInit(argv: string[]): Promise<void> {
  const args = parseArgs(argv);
  const outPath = join(args.repoRoot, ".brewing/dev-env.yaml");
  if (existsSync(outPath) && !args.force) {
    console.error(
      `slowcook dev-env init: ${outPath} already exists. Pass --force to overwrite.`,
    );
    process.exit(64);
  }
  const apps = detectAppsForInit(args.repoRoot, args.appsDir);
  if (apps.length === 0) {
    console.error(
      `slowcook dev-env init: no apps detected under \`${args.appsDir}/\`. Pass --apps-dir <path> or hand-author the config.`,
    );
    process.exit(1);
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderDevEnvYaml(apps), "utf8");
  console.log(`slowcook dev-env init: wrote ${outPath}`);
  console.log(`  apps detected (${apps.length}):`);
  for (const a of apps) {
    console.log(`    - ${a.name} (mode: ${a.mode}, port: ${a.port})`);
  }
  console.log("");
  console.log("Next steps:");
  console.log("  1. Edit ssh_target.{host,user,checkout_dir,key_secret}");
  console.log("  2. Adjust ports if they collide on your deploy box");
  console.log("  3. Add the dev-deploy.yml workflow (see slowcook docs/dev-env-checkpoint-phase-3.md for the canonical shape)");
  console.log(`  4. Set the SSH-key secret named in ssh_target.key_secret on your repo`);
}
