/**
 * `slowcook on-mockup-approved --pr <number>` — 0.16.0-α.25.
 *
 * Called from a workflow that fires on `pull_request.labeled` with
 * label = `slowcook-mockup-approved`. Walks every cost source for the
 * story (refine on the source issue, refine + spec-merge on the spec
 * PR, recipe on the tests PR, vibe + plate on the mockup PR), itemizes
 * each run, and posts (or UPDATES) a cost-rollup audit comment on the
 * originating GitHub issue.
 *
 * α.25 changes vs α.23:
 *  - Walks ALL related sources, not just the mockup PR. Captures
 *    refine + recipe runs that previously went uncounted.
 *  - Itemizes each run (one row per cost marker) instead of grouping
 *    by agent. Includes timestamp, agent, model, $, source link, and
 *    commit SHA when available (parsed from plate's breadcrumb JSON).
 *  - Idempotent: looks for an existing `slowcook:on-mockup-approved`
 *    marker in the issue's comments; updates that comment in place
 *    instead of double-posting.
 *
 * Pairs with on-spec-merged / on-tests-merged / on-brew-merged so the
 * issue thread tells the full pipeline story end-to-end.
 */

import { execSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import YAML from "yaml";
import { Octokit } from "@octokit/rest";

interface Args {
  prNumber: number;
  repoRoot: string;
  owner?: string;
  repo?: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { prNumber: 0, repoRoot: process.cwd() };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    if (arg === "--pr" && next) { args.prNumber = parseInt(next, 10); i++; }
    else if (arg === "--cwd" && next) { args.repoRoot = next; i++; }
    else if (arg === "--owner" && next) { args.owner = next; i++; }
    else if (arg === "--repo" && next) { args.repo = next; i++; }
    else if (arg === "--help" || arg === "-h") { printHelp(); process.exit(0); }
  }
  if (!args.prNumber || isNaN(args.prNumber)) {
    console.error("Missing required --pr <number>");
    printHelp();
    process.exit(64);
  }
  return args;
}

function printHelp(): void {
  console.log(`
slowcook on-mockup-approved — post (or update) a cost rollup on the source issue

Triggered by a workflow listening for pull_request.labeled events on
PRs labeled \`slowcook-mockup\` when the \`slowcook-mockup-approved\`
label is added. Walks every related source (issue, spec PR, tests PR,
mockup PR), itemizes every cost marker, posts a chronological table.

Idempotent: re-running updates the existing rollup comment on the
issue rather than posting a new one.

Usage:
  slowcook on-mockup-approved --pr <number> [options]

Options:
  --pr <number>    Mockup PR number (required)
  --cwd <path>     Repo working directory (default: .)
  --owner <login>  Repo owner (default: detected from git remote)
  --repo <name>    Repo name (default: detected from git remote)

Environment:
  GITHUB_TOKEN  (required)  Token with issues:write + pull-requests:read

Exit codes:
  0   comment posted/updated (or nothing to do)
  2   script error
`);
}

function detectOwnerRepo(cwd: string): { owner: string; repo: string } | null {
  try {
    const url = execSync("git remote get-url origin", {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const m = url.match(/github\.com[:/]([^/]+)\/([^/.]+)(?:\.git)?$/);
    if (m && m[1] && m[2]) return { owner: m[1], repo: m[2] };
  } catch { /* ignore */ }
  return null;
}

const COST_MARKER_RE = /<!--\s*slowcook:cost\s+([^>]+?)\s*-->/g;
const ROLLUP_MARKER = "slowcook:on-mockup-approved";

interface CostRun {
  agent: string;
  usd: number;
  model?: string;
  cli?: string;
  /** When + where this cost was posted. */
  timestamp: string;
  source: { kind: string; number: number; url: string };
  /** Plate's amendment commit SHA when present (from breadcrumb JSON). */
  commitSha?: string | null;
}

/** Parse `key1=value1 key2=value2` pairs from a cost-marker body. */
function parseMarkerKvs(s: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of s.matchAll(/(\w+)=([^\s]+)/g)) {
    out[m[1]!] = m[2]!;
  }
  return out;
}

interface CommentLike {
  body?: string | null;
  created_at?: string;
  html_url?: string;
}

/**
 * 0.16.0-α.25 — legacy-prose fallback for vibe runs that pre-date α.24's
 * structured `<!-- slowcook:cost -->` emission. Vibe ≤α.11 wrote
 * "Generated by `slowcook vibe@VERSION` (spend $X.XXXX)" in its PR
 * body. We pluck that out so dogfood rollups stay accurate.
 */
const VIBE_LEGACY_PROSE_RE =
  /Generated by `slowcook vibe@([^`]+)`[^(]*\(spend \$([0-9.]+)\)/;

function extractCostRunsFromBody(
  body: string,
  source: { kind: string; number: number; url: string },
  timestamp: string
): CostRun[] {
  const out: CostRun[] = [];
  // Legacy prose vibe — only fires when no structured vibe marker
  // also exists (so we don't double-count post-α.24 vibe runs).
  if (!/slowcook:cost\s+agent=vibe/.test(body)) {
    const proseMatch = body.match(VIBE_LEGACY_PROSE_RE);
    if (proseMatch) {
      const usd = parseFloat(proseMatch[2]!);
      if (!Number.isNaN(usd)) {
        out.push({
          agent: "vibe",
          usd,
          cli: proseMatch[1],
          timestamp,
          source,
          commitSha: null,
        });
      }
    }
  }
  COST_MARKER_RE.lastIndex = 0;
  // For plate-reply breadcrumbs, look for the amendment_commit so we
  // can link to the diff. Same comment body usually carries both
  // markers (cost + breadcrumb).
  let amendmentCommit: string | null = null;
  const breadcrumbMatch = body.match(/slowcook:plate-reply\s*\n\s*(\{[\s\S]*?\})\s*\n\s*-->/);
  if (breadcrumbMatch && breadcrumbMatch[1]) {
    try {
      const payload = JSON.parse(breadcrumbMatch[1]) as { amendment_commit?: string | null };
      if (payload.amendment_commit) amendmentCommit = payload.amendment_commit;
    } catch { /* ignore */ }
  }
  let m: RegExpExecArray | null;
  while ((m = COST_MARKER_RE.exec(body)) !== null) {
    const kvs = parseMarkerKvs(m[1]!);
    const usd = parseFloat(kvs["usd"] ?? "0");
    if (!kvs["agent"] || Number.isNaN(usd)) continue;
    out.push({
      agent: kvs["agent"]!,
      usd,
      model: kvs["model"],
      cli: kvs["cli"],
      timestamp,
      source,
      commitSha: amendmentCommit,
    });
  }
  return out;
}

async function fetchPrComments(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number
): Promise<CommentLike[]> {
  return octokit.paginate(octokit.rest.issues.listComments, {
    owner, repo, issue_number: prNumber, per_page: 100,
  });
}

async function fetchIssueComments(
  octokit: Octokit,
  owner: string,
  repo: string,
  issueNumber: number
): Promise<CommentLike[]> {
  return octokit.paginate(octokit.rest.issues.listComments, {
    owner, repo, issue_number: issueNumber, per_page: 100,
  });
}

interface RelatedSource {
  kind: "spec" | "tests" | "mockup" | "brew";
  number: number;
  url: string;
  body?: string | null;
  bodyTimestamp?: string;
}

async function findRelatedPrs(
  octokit: Octokit,
  owner: string,
  repo: string,
  storyId: string
): Promise<RelatedSource[]> {
  // Search PRs by title for `story-{id}`. Captures spec, tests,
  // mockup, brew PRs all in one pass. Excludes superseded specs etc.
  const q = `repo:${owner}/${repo} is:pr in:title story-${storyId}`;
  const res = await octokit.rest.search.issuesAndPullRequests({ q, per_page: 50 });
  const out: RelatedSource[] = [];
  for (const item of res.data.items) {
    if (!item.pull_request) continue;
    const title = item.title.toLowerCase();
    let kind: RelatedSource["kind"];
    if (title.startsWith("spec:")) kind = "spec";
    else if (title.startsWith("tests:") || title.startsWith("recipe:")) kind = "tests";
    else if (title.startsWith("mockup:")) kind = "mockup";
    else if (title.startsWith("brew") || title.startsWith("brew (")) kind = "brew";
    else continue;  // unknown — likely a manual PR; skip
    out.push({
      kind,
      number: item.number,
      url: item.html_url,
      body: item.body,
      bodyTimestamp: item.created_at,
    });
  }
  return out;
}

export async function onMockupApproved(argv: string[]): Promise<void> {
  const args = parseArgs(argv);

  const token = process.env["GITHUB_TOKEN"];
  if (!token) {
    console.error("GITHUB_TOKEN environment variable is not set.");
    process.exit(2);
  }

  let owner = args.owner;
  let repo = args.repo;
  if (!owner || !repo) {
    const detected = detectOwnerRepo(args.repoRoot);
    if (!detected) {
      console.error("Could not detect owner/repo from git remote. Pass --owner and --repo.");
      process.exit(2);
    }
    owner = owner ?? detected.owner;
    repo = repo ?? detected.repo;
  }

  const octokit = new Octokit({ auth: token, userAgent: "slowcook-ai/cli" });

  // 1. Fetch the mockup PR to get its head ref + verify shape.
  const pr = await octokit.rest.pulls.get({ owner, repo, pull_number: args.prNumber });
  const headRef = pr.data.head.ref;
  const headRefMatch = headRef.match(/^slowcook\/mockup\/story-([\w-]+)$/);
  if (!headRefMatch || !headRefMatch[1]) {
    console.error(
      `PR #${args.prNumber} head ref "${headRef}" doesn't match slowcook/mockup/story-N. Skipping.`
    );
    return;
  }
  const storyId = headRefMatch[1];

  // 2. Read the spec to find source_issue.
  const specPath = join(args.repoRoot, "specs", `story-${storyId}.yaml`);
  if (!existsSync(specPath)) {
    console.error(`Spec not found at ${specPath}; cannot resolve source_issue.`);
    process.exit(0);
  }
  const spec = YAML.parse(readFileSync(specPath, "utf8")) as { source_issue?: string };
  if (!spec.source_issue) {
    console.log(`Spec story-${storyId} has no source_issue. Nothing to bill.`);
    return;
  }
  const issueMatchYaml = spec.source_issue.match(/^#?(\d+)$/);
  if (!issueMatchYaml || !issueMatchYaml[1]) {
    console.error(`spec source_issue "${spec.source_issue}" not numeric.`);
    process.exit(0);
  }
  const issueNumber = parseInt(issueMatchYaml[1], 10);

  // 3. Walk every related source for cost markers.
  const issue = await octokit.rest.issues.get({ owner, repo, issue_number: issueNumber });
  const issueUrl = issue.data.html_url;
  const allRuns: CostRun[] = [];

  // 3a. Issue body + comments (refine often posts here).
  if (issue.data.body) {
    allRuns.push(...extractCostRunsFromBody(issue.data.body, { kind: "issue", number: issueNumber, url: issueUrl }, issue.data.created_at));
  }
  const issueComments = await fetchIssueComments(octokit, owner, repo, issueNumber);
  for (const c of issueComments) {
    if (!c.body) continue;
    allRuns.push(...extractCostRunsFromBody(c.body, { kind: "issue", number: issueNumber, url: c.html_url ?? issueUrl }, c.created_at ?? ""));
  }

  // 3b. Every PR matching `story-{id}` in title (spec / tests / mockup / brew).
  const relatedPrs = await findRelatedPrs(octokit, owner, repo, storyId);
  for (const pr of relatedPrs) {
    // PR body (vibe's initial cost lives here for the mockup PR).
    if (pr.body) {
      allRuns.push(...extractCostRunsFromBody(pr.body, { kind: pr.kind, number: pr.number, url: pr.url }, pr.bodyTimestamp ?? ""));
    }
    // PR comments.
    const prComments = await fetchPrComments(octokit, owner, repo, pr.number);
    for (const c of prComments) {
      if (!c.body) continue;
      allRuns.push(...extractCostRunsFromBody(c.body, { kind: pr.kind, number: pr.number, url: c.html_url ?? pr.url }, c.created_at ?? ""));
    }
  }

  // Sort chronologically.
  allRuns.sort((a, b) => (a.timestamp || "").localeCompare(b.timestamp || ""));

  // 4. Build the rollup body.
  const total = allRuns.reduce((s, r) => s + r.usd, 0);
  const totalsByAgent = new Map<string, { runs: number; usd: number }>();
  for (const r of allRuns) {
    const t = totalsByAgent.get(r.agent) ?? { runs: 0, usd: 0 };
    t.runs += 1;
    t.usd += r.usd;
    totalsByAgent.set(r.agent, t);
  }

  const lines: string[] = [];
  lines.push(`### slowcook · mockup approved (story-${storyId})`);
  lines.push("");
  lines.push(
    `Mockup PR #${args.prNumber} signed off; \`slowcook-mockup-approved\` label applied. ` +
      `Plate refuses further amendments. **Next**: merge the PR to fire \`brew --mode plate\` ` +
      `(once the recipe-tests PR is also merged).`
  );
  lines.push("");

  // Itemized rollup — one row per cost marker.
  lines.push(`#### Itemised runs (${allRuns.length})`);
  lines.push("");
  if (allRuns.length === 0) {
    lines.push("_No cost markers found across this story's PRs + issue. (Likely a pre-α.24 vibe run that didn't emit the structured marker.)_");
  } else {
    lines.push("| # | When | Agent | Model | Source | $ | Diff |");
    lines.push("|--:|---|---|---|---|---:|---|");
    let i = 1;
    for (const r of allRuns) {
      const when = r.timestamp ? new Date(r.timestamp).toISOString().slice(0, 16).replace("T", " ") : "—";
      const sourceLabel = `${r.source.kind} #${r.source.number}`;
      const sourceLink = `[${sourceLabel}](${r.source.url})`;
      const diff = r.commitSha
        ? `[\`${r.commitSha.slice(0, 7)}\`](https://github.com/${owner}/${repo}/commit/${r.commitSha})`
        : "—";
      lines.push(
        `| ${i} | ${when} | \`${r.agent}\` | ${r.model ? `\`${r.model}\`` : "—"} | ${sourceLink} | $${r.usd.toFixed(4)} | ${diff} |`
      );
      i++;
    }
  }
  lines.push("");

  // Totals by agent.
  lines.push(`#### Totals by agent`);
  lines.push("");
  lines.push("| Agent | Runs | $ |");
  lines.push("|---|---:|---:|");
  for (const [agent, t] of [...totalsByAgent.entries()].sort()) {
    lines.push(`| \`${agent}\` | ${t.runs} | $${t.usd.toFixed(4)} |`);
  }
  lines.push(`| **Total so far** | **${allRuns.length}** | **$${total.toFixed(4)}** |`);
  lines.push("");

  lines.push(
    `_Post-merge brew run will add its own line; \`on-brew-merged\` updates this comment when that lands._`
  );
  lines.push("");
  lines.push(
    `<!-- ${ROLLUP_MARKER} pr=${args.prNumber} story=${storyId} usd=${total.toFixed(4)} runs=${allRuns.length} -->`
  );
  const newBody = lines.join("\n");

  // 5. Post or update the rollup comment on the source issue.
  const existingComments = await fetchIssueComments(octokit, owner, repo, issueNumber);
  const existing = existingComments.find((c) => (c.body ?? "").includes(ROLLUP_MARKER)) as
    | (CommentLike & { id: number })
    | undefined;
  if (existing) {
    await octokit.rest.issues.updateComment({
      owner, repo, comment_id: existing.id, body: newBody,
    });
    console.log(
      `Updated existing rollup comment on issue #${issueNumber} (story-${storyId}, ${allRuns.length} runs / $${total.toFixed(4)} total).`
    );
  } else {
    await octokit.rest.issues.createComment({
      owner, repo, issue_number: issueNumber, body: newBody,
    });
    console.log(
      `Posted new rollup comment on issue #${issueNumber} (story-${storyId}, ${allRuns.length} runs / $${total.toFixed(4)} total).`
    );
  }
}
