import type { CodeMap } from "./scan.js";

export const CODE_MAP_JSON_PATH = ".brewing/code-map.json";
export const CODE_MAP_MD_PATH = ".brewing/code-map.md";

export function renderJson(map: CodeMap): string {
  return JSON.stringify(map, null, 2) + "\n";
}

/**
 * Render a human-readable markdown view. Optimised for two audiences:
 *  - contributors skimming the map via the PR diff view, and
 *  - the brewing agent reading it as a flat context block.
 *
 * Keep sections compact; JSDoc summaries are trimmed to a single line.
 */
export function renderMarkdown(map: CodeMap): string {
  const lines: string[] = [];
  lines.push(`# Code Map`);
  lines.push("");
  lines.push(
    `_Generated by slowcook ${map.slowcook_version} at ${map.generated_at}. Regenerate with \`npx slowcook map generate\`. Do not hand-edit._`
  );
  lines.push("");

  section(lines, "API routes", map.api_routes.length);
  if (map.api_routes.length > 0) {
    lines.push("");
    lines.push("| Method | Path | File:Line | Function | Summary |");
    lines.push("|---|---|---|---|---|");
    for (const r of map.api_routes) {
      lines.push(
        `| \`${r.method}\` | \`${r.path}\` | \`${fileLine(r.file, r.line)}\` | \`${r.function}\` | ${oneLine(r.jsdoc)} |`
      );
    }
  }
  lines.push("");

  section(lines, "Pages", map.pages.length);
  if (map.pages.length > 0) {
    lines.push("");
    lines.push("| Path | Component | File:Line | Summary |");
    lines.push("|---|---|---|---|");
    for (const p of map.pages) {
      lines.push(
        `| \`${p.path}\` | ${p.component ? `\`${p.component}\`` : "—"} | \`${fileLine(p.file, p.line)}\` | ${oneLine(p.jsdoc)} |`
      );
    }
  }
  lines.push("");

  section(lines, "Components", map.components.length);
  if (map.components.length > 0) {
    lines.push("");
    lines.push("| Name | Export | Props | File:Line | Callers | Summary |");
    lines.push("|---|---|---|---|---|---|");
    for (const c of map.components) {
      lines.push(
        `| \`${c.name}\` | ${c.exportKind} | ${c.props_type ? `\`${c.props_type}\`` : "—"} | \`${fileLine(c.file, c.line)}\` | ${callersCell(c.callers)} | ${oneLine(c.jsdoc)} |`
      );
    }
  }
  lines.push("");

  section(lines, "Helpers", map.helpers.length);
  if (map.helpers.length > 0) {
    lines.push("");
    lines.push("| Name | Kind | File:Line | Callers | Signature | Summary |");
    lines.push("|---|---|---|---|---|---|");
    for (const h of map.helpers) {
      lines.push(
        `| \`${h.name}\` | ${h.kind} | \`${fileLine(h.file, h.line)}\` | ${callersCell(h.callers)} | \`${escapeTable(h.signature)}\` | ${oneLine(h.jsdoc)} |`
      );
    }
  }
  lines.push("");

  section(lines, "Types", map.types.length);
  if (map.types.length > 0) {
    lines.push("");
    for (const t of map.types) {
      const loc = fileLine(t.file, t.line);
      const usage = t.callers !== undefined ? ` · ${t.callers} callers` : "";
      lines.push(`### ${t.name} (${t.kind}) — \`${loc}\`${usage}`);
      if (t.jsdoc) {
        lines.push("");
        lines.push(`> ${oneLine(t.jsdoc)}`);
      }
      lines.push("");
      lines.push("```ts");
      lines.push(t.declaration);
      lines.push("```");
      lines.push("");
    }
  }

  return lines.join("\n");
}

function section(lines: string[], label: string, count: number): void {
  lines.push(`## ${label} (${count})`);
}

function oneLine(s: string | undefined): string {
  if (!s) return "";
  const first = s.split("\n")[0] ?? "";
  return first.replace(/\|/g, "\\|").trim();
}

function escapeTable(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function fileLine(file: string, line: number | undefined): string {
  return line !== undefined ? `${file}:${line}` : file;
}

function callersCell(n: number | undefined): string {
  return n === undefined ? "—" : String(n);
}

/**
 * Compare two maps for source-tree equality. Ignores all metadata that
 * can differ between generations without the source having changed —
 * \`generated_at\` (always different), \`slowcook_version\` (differs across
 * CLI upgrades), \`repo_root\` (cwd-dependent). Only the scanned entities
 * matter for staleness: routes, pages, components, helpers, types.
 *
 * Without this, bumping \`.brewing/slowcook-cli-version\` would force every
 * consumer to regenerate + commit their map on the same PR — defeating
 * the point of a one-line version bump.
 */
export function mapsEqual(a: CodeMap, b: CodeMap): boolean {
  const canonical = (m: CodeMap) =>
    JSON.stringify({
      api_routes: m.api_routes,
      pages: m.pages,
      components: m.components,
      helpers: m.helpers,
      types: m.types,
    });
  return canonical(a) === canonical(b);
}
