import { describe, it, expect } from "vitest";
import { mkdtempSync, readFileSync, existsSync, rmSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  resolveDataSeamRoot,
  writeMockFixtures,
  renderMockFile,
  renderStubFile,
  SLOWCOOK_STUB_MARKER,
} from "./mock-fixtures.js";
import type { Spec } from "@slowcook-ai/core";

function mkRepo(): string {
  return mkdtempSync(join(tmpdir(), "slowcook-mock-fixtures-"));
}

function baseSpec(extra: Partial<Spec> = {}): Spec {
  return {
    story_id: "042",
    title: "test",
    status: "active",
    created_at: "2026-04-25T00:00:00Z",
    supersedes: [],
    superseded_by: null,
    actors: [],
    preconditions: [],
    invariants: [],
    acceptance_scenarios: [],
    non_goals: [],
    ...extra,
  };
}

describe("renderMockFile", () => {
  it("emits one named export per seed key with auto-gen header + as const", () => {
    const out = renderMockFile("notifications", "042", {
      list: [{ id: "n-1", actor_handle: "@a" }],
      unread_count: 1,
    });
    expect(out).toContain("Auto-generated by `slowcook refine` for story-042");
    expect(out).toContain("Brew replaces the sibling `notifications.ts`");
    expect(out).toContain('export const list = [\n  {\n    "id": "n-1"');
    expect(out).toContain("export const unread_count = 1 as const;");
  });

  it("rejects export names that aren't valid TS identifiers", () => {
    expect(() =>
      renderMockFile("d", "1", { "bad-name": [] })
    ).toThrow(/not a valid TS identifier/);
  });

  it("supports primitive + array + nested object values", () => {
    const out = renderMockFile("d", "1", {
      n: 7,
      arr: [1, 2, 3],
      obj: { a: { b: "c" } },
    });
    expect(out).toContain("export const n = 7 as const;");
    expect(out).toContain("export const arr = [\n  1,\n  2,\n  3\n] as const;");
    expect(out).toMatch(/export const obj = \{[\s\S]*"b": "c"[\s\S]*\} as const;/);
  });
});

describe("writeMockFixtures", () => {
  it("skips when spec has no proposals.fixtures block", () => {
    const repo = mkRepo();
    try {
      const result = writeMockFixtures(repo, baseSpec());
      expect(result.written).toEqual([]);
      expect(result.skippedReason).toContain("no proposals.fixtures");
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  it("skips when fixtures status is rejected", () => {
    const repo = mkRepo();
    try {
      const result = writeMockFixtures(
        repo,
        baseSpec({
          proposals: {
            fixtures: {
              status: "rejected",
              proposed_by: "refine-agent",
              by_domain: {
                notifications: { seed: { list: [] } },
              },
            },
          },
        })
      );
      expect(result.written).toEqual([]);
      expect(result.skippedReason).toContain("rejected");
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  it("writes a sibling .ts stub re-exporting the .mock.ts (α.2 data-layer seam)", () => {
    const repo = mkRepo();
    try {
      writeMockFixtures(
        repo,
        baseSpec({
          proposals: {
            fixtures: {
              status: "pending",
              proposed_by: "refine-agent",
              by_domain: {
                notifications: { seed: { list: [{ id: "n-1" }] } },
              },
            },
          },
        })
      );
      const stub = readFileSync(
        join(repo, "src/lib/data/notifications.ts"),
        "utf8"
      );
      expect(stub).toContain(SLOWCOOK_STUB_MARKER);
      expect(stub).toContain('export * from "./notifications.mock.js";');
      expect(stub).toContain("Auto-generated stub by `slowcook refine` for story-042");
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  it("renderStubFile produces a brew-detectable @slowcook-stub marker", () => {
    const out = renderStubFile("bookmarks", "099");
    expect(out).toContain(SLOWCOOK_STUB_MARKER);
    expect(out).toContain('export * from "./bookmarks.mock.js";');
    // Brew's detection regex (whatever it ends up being) should match
    // both the marker AND the export line as separate signals.
    expect(out).toMatch(/@slowcook-stub/);
    expect(out).toMatch(/export \* from "\.\/bookmarks\.mock\.js"/);
  });

  it("writes one .mock.ts file per domain into src/lib/data/", () => {
    const repo = mkRepo();
    try {
      const result = writeMockFixtures(
        repo,
        baseSpec({
          proposals: {
            fixtures: {
              status: "pending",
              proposed_by: "refine-agent",
              by_domain: {
                notifications: {
                  seed: {
                    list: [
                      { id: "n-1", actor_handle: "@alice", read_at: null },
                    ],
                    unread_count: 1,
                  },
                },
                bookmarks: {
                  seed: {
                    list: [{ rewo_id: "r-1", added_at: "2026-01-01T00:00:00Z" }],
                  },
                },
              },
            },
          },
        })
      );
      expect(result.written.sort()).toEqual([
        "src/lib/data/bookmarks.mock.ts",
        "src/lib/data/bookmarks.ts",
        "src/lib/data/notifications.mock.ts",
        "src/lib/data/notifications.ts",
      ]);
      const notif = readFileSync(
        join(repo, "src/lib/data/notifications.mock.ts"),
        "utf8"
      );
      expect(notif).toContain("export const list");
      expect(notif).toContain("export const unread_count = 1 as const;");
      expect(existsSync(join(repo, "src/lib/data/bookmarks.mock.ts"))).toBe(
        true
      );
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  it("rejects domain names with path separators or uppercase", () => {
    const repo = mkRepo();
    try {
      expect(() =>
        writeMockFixtures(
          repo,
          baseSpec({
            proposals: {
              fixtures: {
                status: "pending",
                proposed_by: "refine-agent",
                by_domain: {
                  "../escape": { seed: {} },
                },
              },
            },
          })
        )
      ).toThrow(/Invalid fixture domain/);
      expect(() =>
        writeMockFixtures(
          repo,
          baseSpec({
            proposals: {
              fixtures: {
                status: "pending",
                proposed_by: "refine-agent",
                by_domain: {
                  Notifications: { seed: {} },
                },
              },
            },
          })
        )
      ).toThrow(/Invalid fixture domain/);
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  it("is idempotent: same fixtures → byte-identical output", () => {
    const repo = mkRepo();
    try {
      const spec = baseSpec({
        proposals: {
          fixtures: {
            status: "pending",
            proposed_by: "refine-agent",
            by_domain: {
              notifications: { seed: { list: [{ id: "n-1" }] } },
            },
          },
        },
      });
      writeMockFixtures(repo, spec);
      const first = readFileSync(
        join(repo, "src/lib/data/notifications.mock.ts"),
        "utf8"
      );
      writeMockFixtures(repo, spec);
      const second = readFileSync(
        join(repo, "src/lib/data/notifications.mock.ts"),
        "utf8"
      );
      expect(second).toBe(first);
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });
});

// ── #238 regression: fixtures land in the package that owns the data seam ──
describe("resolveDataSeamRoot", () => {
  it("prefers an existing populated seam dir in a sub-package over root src/lib/data", () => {
    const root = mkdtempSync(join(tmpdir(), "mf-seam-"));
    try {
      mkdirSync(join(root, "mock", "src", "data"), { recursive: true });
      writeFileSync(join(root, "mock", "package.json"), "{}");
      writeFileSync(join(root, "mock", "src", "data", "wallet-dash.ts"), "export {};\n");
      expect(resolveDataSeamRoot(root)).toBe("mock/src/data");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("falls back to the legacy root path on greenfield repos", () => {
    const root = mkdtempSync(join(tmpdir(), "mf-green-"));
    try {
      expect(resolveDataSeamRoot(root)).toBe("src/lib/data");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
