import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Spec } from "@slowcook-ai/core";

/**
 * 0.14.0-α.1 (mockup-first refinement) — turn the spec's
 * `proposals.fixtures.by_domain` block into one `<domain>.mock.ts`
 * file per domain under `src/lib/data/`.
 *
 * Output shape (deterministic — no LLM in the loop):
 *
 *   ```ts
 *   // src/lib/data/notifications.mock.ts
 *   //
 *   // Auto-generated by slowcook refine for story-N (mockup-first
 *   // data-layer seam). Hand-authored fixtures land here so the
 *   // generated mockup is behaviorally complete without a real
 *   // backend. Brew replaces the sibling `notifications.ts` (the
 *   // throwing stub) with a real implementation; this file stays
 *   // as reference data for tier-1 tests.
 *
 *   export const list = [
 *     { id: "n-1", actor_handle: "@alice", read_at: null },
 *   ];
 *
 *   export const unread_count = 1;
 *   ```
 *
 * Pure: no LLM, no network, no filesystem walk — just JSON.stringify
 * + light formatting. Idempotent: writing the same fixtures produces
 * byte-identical output.
 */

export interface MockFixtureWriteResult {
  written: string[];
  skippedReason?: string;
}

/** Marker brew searches for to identify files it should replace with real implementations. */
export const SLOWCOOK_STUB_MARKER = "@slowcook-stub" as const;

const VALID_DOMAIN = /^[a-z][a-z0-9_-]*$/;

export function writeMockFixtures(
  repoRoot: string,
  spec: Spec
): MockFixtureWriteResult {
  const fx = spec.proposals?.fixtures;
  if (!fx) {
    return { written: [], skippedReason: "no proposals.fixtures block in spec" };
  }
  if (fx.status === "rejected") {
    return { written: [], skippedReason: "proposals.fixtures status is rejected" };
  }
  if (!fx.by_domain || Object.keys(fx.by_domain).length === 0) {
    return {
      written: [],
      skippedReason: "proposals.fixtures.by_domain is empty",
    };
  }

  const written: string[] = [];
  for (const [domain, payload] of Object.entries(fx.by_domain) as [
    string,
    { seed: Record<string, unknown> }
  ][]) {
    if (!VALID_DOMAIN.test(domain)) {
      throw new Error(
        `Invalid fixture domain '${domain}': must match ${VALID_DOMAIN} (lowercase, no path separators)`
      );
    }
    const seed = payload.seed;
    if (!seed || typeof seed !== "object" || Array.isArray(seed)) {
      throw new Error(
        `Fixture domain '${domain}': seed must be a non-empty object of named exports`
      );
    }
    const relPath = join("src/lib/data", `${domain}.mock.ts`);
    const fullPath = join(repoRoot, relPath);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, renderMockFile(domain, spec.story_id, seed), "utf8");
    written.push(relPath);

    // 0.14.0-α.2 — sibling stub `<domain>.ts`. Re-exports the mock
    // fixtures verbatim so the generated mockup renders during PM
    // review. Marked with `@slowcook-stub` so brew can detect + replace
    // it with a real fetch implementation later.
    const stubRelPath = join("src/lib/data", `${domain}.ts`);
    const stubFullPath = join(repoRoot, stubRelPath);
    writeFileSync(stubFullPath, renderStubFile(domain, spec.story_id), "utf8");
    written.push(stubRelPath);
  }
  return { written };
}

export function renderStubFile(domain: string, storyId: string): string {
  return [
    `// src/lib/data/${domain}.ts`,
    `//`,
    `// Auto-generated stub by \`slowcook refine\` for story-${storyId}`,
    `// (0.14 mockup-first data-layer seam).`,
    `//`,
    `// Body: re-export the mock fixtures verbatim so the generated mockup`,
    `// renders during PM review. When brew takes over, this file is`,
    `// REPLACED with a real fetch implementation; the .mock.ts sibling`,
    `// stays as reference data for tier-1 tests.`,
    `//`,
    `// ${SLOWCOOK_STUB_MARKER} — brew identifies + replaces files containing this marker.`,
    ``,
    `export * from "./${domain}.mock.js";`,
    ``,
  ].join("\n");
}

export function renderMockFile(
  domain: string,
  storyId: string,
  seed: Record<string, unknown>
): string {
  const exports: string[] = [];
  for (const [name, value] of Object.entries(seed)) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      throw new Error(
        `Fixture domain '${domain}' export '${name}' is not a valid TS identifier`
      );
    }
    const json = JSON.stringify(value, null, 2);
    exports.push(`export const ${name} = ${json} as const;`);
  }
  const header = [
    `// src/lib/data/${domain}.mock.ts`,
    `//`,
    `// Auto-generated by \`slowcook refine\` for story-${storyId} (0.14 mockup-first`,
    `// data-layer seam). Hand-authored fixtures so the generated mockup is`,
    `// behaviorally complete without a real backend.`,
    `//`,
    `// Brew replaces the sibling \`${domain}.ts\` (the throwing stub) with a`,
    `// real implementation; this file stays as reference data for tier-1 tests.`,
    `// Do not hand-edit — refine regenerates from \`proposals.fixtures.by_domain.${domain}\`.`,
    ``,
  ].join("\n");
  return header + exports.join("\n\n") + "\n";
}
