/**
 * Phase 2C (0.12.12+) — `.brewing/patterns/` directory.
 *
 * Patterns are short markdown recipes hand-written by the project
 * team that describe project-specific conventions: "how cursor
 * pagination works in this codebase", "the standard handler shape
 * with auth + RLS", "how to write a tier-1 test against
 * mockSupabase". They live at `.brewing/patterns/*.md` and are NOT
 * auto-generated by slowcook — the team owns them.
 *
 * Selective loading: brew injects only the *index* (title + one-line
 * summary per pattern) into its cached prefix. The agent decides
 * which patterns are relevant to the current target and reads the
 * full markdown via the existing `read_file` tool. Index-only is
 * cheap (~50 tokens per pattern); the full body only enters context
 * when the agent asks for it.
 *
 * Pattern file convention:
 *
 *   # <Title>
 *
 *   > <One-line summary, used as the index entry.>
 *
 *   ## When to use
 *   ...
 *   ## Example
 *   ```ts
 *   ...
 *   ```
 *
 * The `# Title` and `> Summary` lines are the parts the index needs;
 * everything else is for the agent's eyes once it `read_file`s the
 * pattern.
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

export const PATTERNS_DIR = ".brewing/patterns";

export interface PatternEntry {
  slug: string;
  title: string;
  summary: string | null;
  path: string;
}

/**
 * Walk `.brewing/patterns/*.md` and return one entry per file.
 * Returns an empty array when the directory doesn't exist (the
 * common case on greenfield projects).
 */
export function gatherPatternIndex(repoRoot: string): PatternEntry[] {
  const dir = join(repoRoot, PATTERNS_DIR);
  if (!existsSync(dir)) return [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  const out: PatternEntry[] = [];
  for (const entry of entries.sort()) {
    if (!entry.endsWith(".md")) continue;
    const fullPath = join(dir, entry);
    let stat;
    try {
      stat = statSync(fullPath);
    } catch {
      continue;
    }
    if (!stat.isFile()) continue;
    let src: string;
    try {
      src = readFileSync(fullPath, "utf8");
    } catch {
      continue;
    }
    const slug = entry.replace(/\.md$/, "");
    const { title, summary } = extractTitleAndSummary(src, slug);
    out.push({
      slug,
      title,
      summary,
      path: `${PATTERNS_DIR}/${entry}`,
    });
  }
  return out;
}

/**
 * Render the pattern index as a markdown block for the brew system /
 * cached prefix. Returns an empty string when no patterns exist —
 * caller can drop the block entirely.
 */
export function renderPatternIndexBlock(patterns: PatternEntry[]): string {
  if (patterns.length === 0) return "";
  const lines: string[] = [];
  lines.push("### Project patterns");
  lines.push("");
  lines.push(
    "Reusable code recipes hand-written for this project. Below is the index — title + one-line summary per pattern. " +
      "If a pattern looks relevant to your target, read the full file via " +
      "`read_file('.brewing/patterns/<name>.md')` before writing similar code."
  );
  lines.push("");
  for (const p of patterns) {
    const summary = p.summary ? ` — ${p.summary}` : "";
    lines.push(`- **${p.title}** (\`${p.path}\`)${summary}`);
  }
  return lines.join("\n");
}

function extractTitleAndSummary(
  src: string,
  fallbackSlug: string
): { title: string; summary: string | null } {
  let title: string | null = null;
  let summary: string | null = null;
  const lines = src.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!title) {
      const m = line.match(/^#\s+(.+?)\s*$/);
      if (m && m[1]) {
        title = m[1].trim();
        continue;
      }
    } else if (!summary) {
      const m = line.match(/^>\s+(.+?)\s*$/);
      if (m && m[1]) {
        summary = m[1].trim();
        break;
      }
      // Stop scanning once we hit non-blank content that isn't a blockquote.
      if (line.length > 0) break;
    }
  }
  return {
    title: title ?? fallbackSlug,
    summary,
  };
}
