#!/usr/bin/env bash
# scripts/sync-readme-help.sh — regenerate the auto-generated command
# catalog inside `packages/cli/README.md` from the COMMANDS manifest.
#
# The catalog lives between these markers in the README:
#
#   <!-- COMMANDS BLOCK BEGIN — auto-generated by scripts/sync-readme-help.sh, do not edit by hand -->
#   ...
#   <!-- COMMANDS BLOCK END -->
#
# The CI gate `.github/workflows/readme-help-sync.yml` runs this script
# and fails if it leaves any files modified.
#
# Usage:
#   pnpm -F @slowcook-ai/cli build && bash scripts/sync-readme-help.sh
#
# Why bash, not TypeScript: maintainer-only tool. Bash + awk handles the
# splice in 30 lines; TS would mean dist/, install, etc. for a single
# sed-substitute.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_DIST="$ROOT/packages/cli/dist/cli.js"
README="$ROOT/packages/cli/README.md"

if [ ! -f "$CLI_DIST" ]; then
  echo "missing $CLI_DIST — run \`pnpm -F @slowcook-ai/cli build\` first" >&2
  exit 1
fi

if [ ! -f "$README" ]; then
  echo "missing $README" >&2
  exit 1
fi

BEGIN_MARKER='<!-- COMMANDS BLOCK BEGIN — auto-generated by scripts/sync-readme-help.sh, do not edit by hand -->'
END_MARKER='<!-- COMMANDS BLOCK END -->'

if ! grep -qF "$BEGIN_MARKER" "$README"; then
  echo "missing BEGIN marker in $README:" >&2
  echo "  $BEGIN_MARKER" >&2
  exit 1
fi
if ! grep -qF "$END_MARKER" "$README"; then
  echo "missing END marker in $README" >&2
  exit 1
fi

block_tmp="$(mktemp)"
trap 'rm -f "$block_tmp"' EXIT

node "$CLI_DIST" help --markdown-readme > "$block_tmp"

new_readme_tmp="$(mktemp)"
awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block_file="$block_tmp" '
  BEGIN { skipping = 0 }
  index($0, begin) == 1 {
    print
    while ((getline line < block_file) > 0) print line
    close(block_file)
    skipping = 1
    next
  }
  index($0, end) == 1 {
    skipping = 0
    print
    next
  }
  skipping == 0 { print }
' "$README" > "$new_readme_tmp"

mv "$new_readme_tmp" "$README"
echo "synced $README"
