/**
 * GUCDI — deterministic LCR app generator (pure). The final scaffolding pass of
 * the whole-app `vibe`: turns the LCR plan (routes + personas) into a RUNNABLE,
 * NAVIGABLE Vite/React app — the scaffold (package.json, vite, tailwind v4) + the
 * router (every declared surface a route, no auth walls) + a stub page per route
 * (sets the `@story` marker) — with the **slowcook review-overlay** mounted to
 * provide all REVIEW affordances (persona switch + EPSS epic·persona·scenario·state
 * router + comment capture). Personas live in the overlay's EPSS manifest, NOT in
 * the mock's chrome. No LLM: the skeleton is deterministic; the LLM `vibe surfaces`
 * pass later fills each stub's body. See docs/plans/vibe-whole-mock-lcr.md.
 * The EPSS manifest model (epic·persona·scenario·state, Foundations home for the
 * universal UI-Stack states) is defined in docs/EPSS.md — read it before changing
 * `epssManifestJson`.
 */
import type { LcrPlan } from "./lcr-plan.js";

export interface GenFile {
  /** path relative to the mock root (e.g. "src/App.tsx"). */
  path: string;
  content: string;
}

/** route → React component name: "/admin/workers" → "AdminWorkersPage", "/" → "HomePage". */
export function routeToName(route: string): string {
  const pascal = (raw: string) =>
    raw
      .replace(/[^a-zA-Z0-9]+/g, " ")
      .trim()
      .split(/\s+/)
      .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : ""))
      .join("");
  // Keep param segments as `By<Param>` so `/projects/:projectId` →
  // `ProjectsByProjectIdPage`, not a meaningless `Projects2Page` collision.
  const name = route
    .split("/")
    .filter(Boolean)
    .map((s) => (s.startsWith(":") ? "By" + pascal(s.slice(1)) : pascal(s)))
    .join("");
  return (name || "Home") + "Page";
}

interface RouteEntry {
  route: string;
  component: string;
  personas: string[];
  stories: string[];
  states: string[];
  home: boolean;
}

/** Group surfaces by unique route + assign collision-free component names. */
function routeEntries(plan: LcrPlan): RouteEntry[] {
  const byRoute = new Map<string, RouteEntry>();
  for (const s of plan.surfaces) {
    let e = byRoute.get(s.route);
    if (!e) {
      e = { route: s.route, component: "", personas: [], stories: [], states: [], home: false };
      byRoute.set(s.route, e);
    }
    if (!e.personas.includes(s.persona)) e.personas.push(s.persona);
    if (!e.stories.includes(s.storyId)) e.stories.push(s.storyId);
    for (const st of s.states) if (!e.states.includes(st)) e.states.push(st);
    if (s.home) e.home = true;
  }
  const used = new Set<string>();
  for (const e of byRoute.values()) {
    let name = routeToName(e.route);
    if (used.has(name)) {
      let i = 2;
      while (used.has(`${name.replace(/Page$/, "")}${i}Page`)) i++;
      name = `${name.replace(/Page$/, "")}${i}Page`;
    }
    used.add(name);
    e.component = name;
  }
  return [...byRoute.values()];
}

const j = JSON.stringify;
/** Slug arbitrary text into a stable id segment for the EPSS manifest. */
function textSlug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "x";
}

/** The Foundations showcase route — the ONE home for the universal UI-Stack states. */
const FOUNDATIONS_ROUTE = "/_foundations";

function packageJson(name: string): string {
  return (
    j(
      {
        name: `${name}-lcr-mock`,
        private: true,
        type: "module",
        scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
        dependencies: {
          "@slowcook-ai/review-overlay": "^0.9.0",
          react: "^19.0.0",
          "react-dom": "^19.0.0",
          "react-router-dom": "^7.0.0",
          "drizzle-orm": "^0.36.0",
          "sql.js": "^1.10.3",
        },
        devDependencies: {
          "@tailwindcss/vite": "^4.0.0",
          "@vitejs/plugin-react": "^4.3.0",
          "@types/react": "^19.0.0",
          "@types/react-dom": "^19.0.0",
          "@types/sql.js": "^1.4.9",
          tailwindcss: "^4.0.0",
          typescript: "^5.6.0",
          vite: "^6.0.0",
        },
      },
      null,
      2
    ) + "\n"
  );
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// LCR mock — generated by \`slowcook vibe app\`. sql.js is CJS, so it MUST be
// pre-bundled (\`include\`) or \`import initSqlJs from "sql.js"\` throws
// "does not provide an export" in \`vite dev\` (the HMR review deploy) — even though
// \`vite build\` works. The .wasm is imported separately via \`?url\` (a vite asset,
// unaffected). BrowserRouter needs SPA fallback — vite dev provides it by default.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  optimizeDeps: { include: ["sql.js"] },
});
`;
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name} — LCR</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function tsconfig(): string {
  return (
    j(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          module: "ESNext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          types: ["vite/client"],
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n"
  );
}

function mainTsx(): string {
  return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { App } from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
`;
}

function indexCss(): string {
  return `@import "./design-system/theme.css";

html, body, #root { height: 100%; }
body { margin: 0; background: var(--color-bg); color: var(--color-text); font-family: var(--font-sans, system-ui, sans-serif); }
`;
}

function viteEnvDts(): string {
  return `/// <reference types="vite/client" />
declare module "*?url" { const url: string; export default url; }
`;
}

function useStoryMarker(): string {
  return `import { useEffect } from "react";

/** Sets document.documentElement.dataset.slowcookStory so the review overlay can
 *  attribute LCR comments to the right story (the runtime @story marker). */
export function useStoryMarker(storyId: string): void {
  useEffect(() => {
    const prev = document.documentElement.dataset.slowcookStory;
    document.documentElement.dataset.slowcookStory = storyId;
    return () => {
      if (prev) document.documentElement.dataset.slowcookStory = prev;
      else delete document.documentElement.dataset.slowcookStory;
    };
  }, [storyId]);
}
`;
}

/** lib/use-async.ts — the async producer hook feeding the shared <Async>. */
function useAsyncTs(): string {
  return `import { useEffect, useState } from "react";

export type Async<T> =
  | { loading: true }
  | { loading: false; error: Error }
  | { loading: false; data: T };

/** Run an async producer on mount + when deps change; expose loading / error /
 *  data as a discriminated union consumed by <Async>. */
export function useAsync<T>(fn: () => Promise<T>, deps: unknown[]): Async<T> {
  const [state, setState] = useState<Async<T>>({ loading: true });
  useEffect(() => {
    let live = true;
    setState({ loading: true });
    fn().then(
      (data) => { if (live) setState({ loading: false, data }); },
      (e) => { if (live) setState({ loading: false, error: e instanceof Error ? e : new Error(String(e)) }); }
    );
    return () => { live = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
  return state;
}
`;
}

/** shell/async.tsx — the ONE-OFF loading/error presentation (the UI-Stack universal
 *  states). Every data page wraps its body in <Async>; the spinner, error styling +
 *  animations live in exactly one place. Pages write only the success UI + their
 *  MEANINGFUL data/business states. Showcased once via the Foundations EPSS entry. */
function asyncTsx(): string {
  return `import type { ReactNode } from "react";
import type { Async as AsyncResult } from "../lib/use-async";

const KEYFRAMES = "@keyframes sc-spin{to{transform:rotate(360deg)}}@keyframes sc-fade{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}" +
  ".sc-spinner{width:18px;height:18px;border-radius:999px;border:2px solid var(--color-border);border-top-color:var(--color-brand);animation:sc-spin .7s linear infinite;display:inline-block}" +
  ".sc-error-card{animation:sc-fade .2s ease;border:1px solid var(--color-danger);border-radius:var(--radius-card);padding:18px;color:var(--color-danger);font-size:13.5px;background:color-mix(in srgb,var(--color-danger) 8%,transparent)}";

export function Spinner({ label = "Loading…" }: { label?: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10, padding: 28, color: "var(--color-text-dim)", fontSize: 13.5 }}>
      <style>{KEYFRAMES}</style>
      <span className="sc-spinner" />
      {label}
    </div>
  );
}

export function ErrorState({ message }: { message: string }) {
  return (
    <div className="sc-error-card">
      <style>{KEYFRAMES}</style>
      <b>Something went wrong.</b> {message}
    </div>
  );
}

/** Wrap an async result: shared Spinner while loading, shared ErrorState on
 *  failure, render children with the data on success. */
export function Async<T>({ value, children }: { value: AsyncResult<T>; children: (data: T) => ReactNode }) {
  if (value.loading) return <Spinner />;
  if ("error" in value) return <ErrorState message={value.error.message} />;
  return <>{children(value.data)}</>;
}
`;
}

/** lib/surface.ts — EPSS state binding. The review-overlay writes the selected
 *  epic/persona/scenario/STATE to localStorage; a page reads the active state to
 *  vary its data. (OSS gap: the overlay should export this hook directly.) */
function surfaceTs(): string {
  return `// EPSS state binding — the review-overlay writes the selected state to
// localStorage; a page reads it to vary its data (empty / low-balance / …). This is
// the seam that makes the EPSS state-switcher actually drive the mock.
import { useSyncExternalStore } from "react";

const KEY = "slowcook_test_surface";
const EVENT = "slowcook-test-surface-change";

function read(): string | null {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return null;
    return (JSON.parse(raw) as { stateId?: string }).stateId ?? null;
  } catch {
    return null;
  }
}

function subscribe(cb: () => void): () => void {
  window.addEventListener(EVENT, cb);
  window.addEventListener("storage", cb);
  return () => {
    window.removeEventListener(EVENT, cb);
    window.removeEventListener("storage", cb);
  };
}

/** The EPSS-selected state for the current surface, or \`fallback\` when none is
 *  picked yet. */
export function useSurfaceState(fallback = "populated"): string {
  return useSyncExternalStore(subscribe, read, () => null) ?? fallback;
}
`;
}

/** pages/FoundationsPage.tsx — the ONE home for the universal UI-Stack states. The
 *  Foundations EPSS entry points here; picking loading/empty/error in the palette
 *  previews the shared presentation, so it's reviewable once, never per page. */
function foundationsPageTsx(): string {
  return `import { useStoryMarker } from "../shell/useStoryMarker";
import { useSurfaceState } from "../lib/surface";
import { Spinner, ErrorState } from "../shell/async";

// @story foundations — universal UI-Stack states, shown once.
export function FoundationsPage() {
  useStoryMarker("foundations");
  const state = useSurfaceState("loading");
  return (
    <section>
      <h1 style={{ marginTop: 0 }}>Presentation primitives</h1>
      <p style={{ opacity: 0.7, maxWidth: 560 }}>
        The universal UI-Stack states — <b>loading</b>, <b>empty</b>, <b>error</b> — rendered
        once by the shared <code>&lt;Async&gt;</code> primitive. Every data page reuses these
        instead of redeclaring them. Pick a state in the EPSS palette to preview it.
      </p>
      <div style={{ marginTop: 16, padding: 16, border: "1px solid var(--color-border)", borderRadius: 8 }}>
        {state === "error" ? (
          <ErrorState message="The data source could not be reached." />
        ) : state === "empty" ? (
          <div style={{ padding: 28, textAlign: "center", opacity: 0.7, fontSize: 13.5 }}>Nothing here yet.</div>
        ) : (
          <Spinner />
        )}
      </div>
    </section>
  );
}
`;
}

/** The `surfaces` prop for the overlay's "Viewing as" persona switcher — named
 *  entry points the reviewer hops between (one per persona → its home route). */
function reviewSurfacesTs(plan: LcrPlan): string {
  const surfaces = plan.personas.map((p) => {
    const ps = plan.surfaces.filter((s) => s.persona === p.id);
    const home = ps.find((s) => s.home)?.route ?? ps[0]?.route ?? "/";
    return { label: p.id, home };
  });
  return `// Review surfaces — the overlay's "Viewing as" persona switcher (review
// affordance; lives in the overlay, NOT the mock chrome). One per persona.
export const REVIEW_SURFACES = ${j(surfaces, null, 2)};
`;
}

interface MfState { id: string; label: string; expect?: string }
interface MfScenario { id: string; label: string; route: string; states: MfState[] }
interface MfContext { id: string; label: string; base: string; scenarios: MfScenario[] }
interface MfEpic { id: string; label: string; contexts: MfContext[] }

/** The EPSS testing-surfaces.json manifest. Each acceptance_scenario is a test
 *  CASE: it starts at `route` in a precondition State (the Gherkin "Given") and
 *  walks a Scenario (the "When") to an expected outcome (the "Then"). Grouped
 *  epic ▸ context(persona) ▸ scenario(When) ▸ state(Given). The route is just
 *  where the test starts — NOT the scenario's identity (one route can back many
 *  scenarios). The universal UI-Stack states (loading/empty/error) are NOT
 *  repeated per page; they get ONE "Foundations" home that demos the shared
 *  <Async> primitive. The overlay renders this as the EPSS router and writes the
 *  selection to localStorage for the data adaptor. URL = base + route, so base is
 *  "" (scenarios carry absolute routes). */
export function epssManifestJson(plan: LcrPlan, projectName: string): string {
  // epic -> persona -> scenario(When) -> states(Given), preserving first-seen order.
  const epics = new Map<string, Map<string, Map<string, MfScenario>>>();
  const epicOrder: string[] = [];
  for (const t of plan.epss ?? []) {
    if (!epics.has(t.epic)) { epics.set(t.epic, new Map()); epicOrder.push(t.epic); }
    const personas = epics.get(t.epic)!;
    if (!personas.has(t.persona)) personas.set(t.persona, new Map());
    const scenarios = personas.get(t.persona)!;
    let sc = scenarios.get(t.scenario);
    if (!sc) { sc = { id: textSlug(t.scenario), label: t.scenario, route: t.route, states: [] }; scenarios.set(t.scenario, sc); }
    const stId = textSlug(t.state);
    if (!sc.states.some((s) => s.id === stId)) sc.states.push({ id: stId, label: t.state, ...(t.then ? { expect: t.then } : {}) });
  }
  const epicArr: MfEpic[] = epicOrder.map((epic) => ({
    id: textSlug(epic),
    label: epic,
    contexts: [...epics.get(epic)!.entries()].map(([persona, scenarios]) => ({
      id: textSlug(persona),
      label: persona,
      base: "",
      scenarios: [...scenarios.values()].map((sc) => ({
        ...sc,
        states: sc.states.length ? sc.states : [{ id: "default", label: "default" }],
      })),
    })),
  }));
  // Foundations — the universal UI-Stack states get ONE reviewable home (the shared
  // <Async> primitive showcase) instead of being repeated as a state on every page.
  epicArr.push({
    id: "foundations",
    label: "Foundations",
    contexts: [{
      id: "presentation",
      label: "Presentation",
      base: "",
      scenarios: [{
        id: "async-states",
        label: "Loading, empty & error presentation",
        route: FOUNDATIONS_ROUTE,
        states: [
          { id: "loading", label: "Loading" },
          { id: "empty", label: "Empty" },
          { id: "error", label: "Error" },
        ],
      }],
    }],
  });
  void projectName; // epics carry their own labels now; project name unused
  const manifest = { activeEpicDefault: epicArr[0]?.id ?? "foundations", epics: epicArr };
  return j(manifest, null, 2) + "\n";
}

function shellTsx(): string {
  // Minimal layout. ALL review navigation (persona switch + EPSS surface/state
  // router) is provided by the overlay, not the mock chrome.
  return `import { Outlet } from "react-router-dom";

export function Shell() {
  return (
    <main style={{ minHeight: "100vh", maxWidth: 1100, margin: "0 auto", padding: 24 }}>
      <Outlet />
    </main>
  );
}
`;
}

function pageStub(e: RouteEntry): string {
  const story = e.stories[0] ?? "";
  return `import { useStoryMarker } from "../shell/useStoryMarker";

// @story ${e.stories.map((s) => `story-${s}`).join(", ")}
// STUB — generated by \`slowcook vibe app\`. The page body is a placeholder;
// \`slowcook vibe surfaces\` replaces it with the designed UI rendering via
// ../lib/queries. The route, the @story marker, and the overlay are real.
export function ${e.component}() {
  useStoryMarker(${j(story)});
  return (
    <section>
      <h1 style={{ marginTop: 0 }}>${e.route}</h1>
      <p style={{ opacity: 0.7 }}>
        persona: ${e.personas.join(", ")} · story: ${e.stories.map((s) => `story-${s}`).join(", ")}${e.home ? " · home" : ""}
      </p>
      <p style={{ opacity: 0.7 }}>states to cover: ${e.states.length ? e.states.join(", ") : "(none declared)"}</p>
      <div style={{ marginTop: 16, padding: 16, border: "1px dashed var(--color-border)", borderRadius: 8 }}>
        ▢ page body — run <code>slowcook vibe surfaces</code> to generate the UI (renders via the SQLite data adaptor in <code>../lib/queries</code>). Use the review pill (bottom) to switch persona / EPSS surface.
      </div>
    </section>
  );
}
`;
}

function appTsx(entries: RouteEntry[], owner: string, repo: string): string {
  const imports = entries.map((e) => `import { ${e.component} } from "./pages/${e.component}";`).join("\n");
  const routes = entries.map((e) => `          <Route path=${j(e.route)} element={<${e.component} />} />`).join("\n");
  const homeRoute = entries.find((e) => e.home)?.route ?? entries[0]?.route ?? "/";
  return `import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { SlowcookReviewOverlay } from "@slowcook-ai/review-overlay/react";
import { Shell } from "./shell/Shell";
import { REVIEW_SURFACES } from "./review-surfaces";
import { FoundationsPage } from "./pages/FoundationsPage";
${imports}

// LCR app — generated by \`slowcook vibe app\`. Every declared surface is a route;
// no auth guards (barrier-free review). The slowcook review-overlay provides ALL
// review affordances — the "Viewing as" persona switcher (REVIEW_SURFACES) and the
// EPSS epic·persona·scenario·state router (/testing-surfaces.json) — so personas
// live in the overlay, not the mock chrome. BrowserRouter so the overlay's
// pushState navigation resolves to real routes.
export function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<Shell />}>
${routes}
          <Route path=${j(FOUNDATIONS_ROUTE)} element={<FoundationsPage />} />
          <Route path="/" element={<Navigate to=${j(homeRoute)} replace />} />
        </Route>
      </Routes>
      <SlowcookReviewOverlay
        enabled
        reviewMode="lcr"
        owner=${j(owner)}
        repo=${j(repo)}
        surfaces={REVIEW_SURFACES}
        testingSurfacesUrl="/testing-surfaces.json"
      />
    </BrowserRouter>
  );
}
`;
}

/** The `.brewing/mock.yaml` content — declares the LCR shape so run-mock + the
 *  overlay behave whole-app (device-flow auth, overlay on every route). */
export function mockYaml(): string {
  return `# Generated by \`slowcook vibe app\`. Whole-app LCR mock.
schema_version: 1
shape: vite
review_mode: lcr
mock_root: mock
design_system_dir: mock/src/design-system
screens_root: mock/src/pages
router_file: mock/src/App.tsx
`;
}

/** Build the full deterministic LCR app file set from the plan. */
export function generateLcrApp(plan: LcrPlan, opts: { projectName: string; owner?: string; repo?: string }): GenFile[] {
  const entries = routeEntries(plan);
  const owner = opts.owner ?? "";
  const repo = opts.repo ?? "";
  const files: GenFile[] = [
    { path: "package.json", content: packageJson(opts.projectName) },
    { path: "vite.config.ts", content: viteConfig() },
    { path: "index.html", content: indexHtml(opts.projectName) },
    { path: "tsconfig.json", content: tsconfig() },
    { path: "src/main.tsx", content: mainTsx() },
    { path: "src/index.css", content: indexCss() },
    { path: "src/vite-env.d.ts", content: viteEnvDts() },
    { path: "src/review-surfaces.ts", content: reviewSurfacesTs(plan) },
    { path: "src/shell/useStoryMarker.ts", content: useStoryMarker() },
    { path: "src/shell/Shell.tsx", content: shellTsx() },
    { path: "src/shell/async.tsx", content: asyncTsx() },
    { path: "src/lib/use-async.ts", content: useAsyncTs() },
    { path: "src/lib/surface.ts", content: surfaceTs() },
    { path: "src/pages/FoundationsPage.tsx", content: foundationsPageTsx() },
    { path: "src/App.tsx", content: appTsx(entries, owner, repo) },
    { path: "public/testing-surfaces.json", content: epssManifestJson(plan, opts.projectName) },
  ];
  for (const e of entries) files.push({ path: `src/pages/${e.component}.tsx`, content: pageStub(e) });
  return files;
}
