/**
 * GUCDI — deterministic LCR app generator (pure). The final scaffolding pass of
 * the whole-app `vibe`: turns the LCR plan (routes + personas) into a RUNNABLE,
 * NAVIGABLE Vite/React app — the scaffold (package.json, vite, tailwind v4) + the
 * router (every declared surface reachable, no auth walls) + the persona shell
 * (chrome-aware nav + persona/theme switcher) + a stub page per route (sets the
 * `@story` marker, shows the surface's personas/states). No LLM: the SKELETON is
 * deterministic from the plan; the LLM `vibe surfaces` pass later replaces each
 * stub's body with the designed UI (rendering via the queries.ts adaptor).
 *
 * Returns a list of files; the IO (writing them) is in index.ts. See
 * docs/plans/vibe-whole-mock-lcr.md.
 */
import type { LcrPlan } from "./lcr-plan.js";

export interface GenFile {
  /** path relative to the mock root (e.g. "src/App.tsx"), except mockYaml. */
  path: string;
  content: string;
}

/** route → React component name: "/admin/workers" → "AdminWorkersPage", "/" → "HomePage". */
export function routeToName(route: string): string {
  const name = route
    .split("/")
    .filter(Boolean)
    .filter((s) => !s.startsWith(":"))
    .map((s) =>
      s
        .replace(/[^a-zA-Z0-9]+/g, " ")
        .trim()
        .split(/\s+/)
        .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : ""))
        .join("")
    )
    .join("");
  return (name || "Home") + "Page";
}

interface RouteEntry {
  route: string;
  component: string;
  personas: string[];
  stories: string[];
  states: string[];
  home: boolean;
}

/** Group surfaces by unique route + assign collision-free component names. */
function routeEntries(plan: LcrPlan): RouteEntry[] {
  const byRoute = new Map<string, RouteEntry>();
  for (const s of plan.surfaces) {
    let e = byRoute.get(s.route);
    if (!e) {
      e = { route: s.route, component: "", personas: [], stories: [], states: [], home: false };
      byRoute.set(s.route, e);
    }
    if (!e.personas.includes(s.persona)) e.personas.push(s.persona);
    if (!e.stories.includes(s.storyId)) e.stories.push(s.storyId);
    for (const st of s.states) if (!e.states.includes(st)) e.states.push(st);
    if (s.home) e.home = true;
  }
  const used = new Set<string>();
  for (const e of byRoute.values()) {
    let name = routeToName(e.route);
    if (used.has(name)) {
      let i = 2;
      while (used.has(`${name.replace(/Page$/, "")}${i}Page`)) i++;
      name = `${name.replace(/Page$/, "")}${i}Page`;
    }
    used.add(name);
    e.component = name;
  }
  return [...byRoute.values()];
}

const j = JSON.stringify;

function packageJson(name: string): string {
  return (
    j(
      {
        name: `${name}-lcr-mock`,
        private: true,
        type: "module",
        scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
        dependencies: {
          react: "^19.0.0",
          "react-dom": "^19.0.0",
          "react-router-dom": "^7.0.0",
          "drizzle-orm": "^0.36.0",
          "sql.js": "^1.10.3",
        },
        devDependencies: {
          "@tailwindcss/vite": "^4.0.0",
          "@vitejs/plugin-react": "^4.3.0",
          "@types/react": "^19.0.0",
          "@types/react-dom": "^19.0.0",
          "@types/sql.js": "^1.4.9",
          tailwindcss: "^4.0.0",
          typescript: "^5.6.0",
          vite: "^6.0.0",
        },
      },
      null,
      2
    ) + "\n"
  );
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// LCR mock — generated by \`slowcook vibe app\`. sql.js ships a .wasm we import
// via ?url; exclude it from dep-optimisation so the asset resolves.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  optimizeDeps: { exclude: ["sql.js"] },
});
`;
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name} — LCR</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function tsconfig(): string {
  return (
    j(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          module: "ESNext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          types: ["vite/client"],
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n"
  );
}

function mainTsx(): string {
  return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { App } from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
`;
}

function indexCss(): string {
  // theme.css already @imports tailwindcss + declares @theme tokens + mode vars.
  return `@import "./design-system/theme.css";

html, body, #root { height: 100%; }
body { margin: 0; background: var(--color-bg); color: var(--color-text); font-family: var(--font-sans, system-ui, sans-serif); }
`;
}

function viteEnvDts(): string {
  return `/// <reference types="vite/client" />
declare module "*?url" { const url: string; export default url; }
`;
}

function useStoryMarker(): string {
  return `import { useEffect } from "react";

/** Sets document.documentElement.dataset.slowcookStory so the review overlay can
 *  attribute LCR comments to the right story (the runtime @story marker). */
export function useStoryMarker(storyId: string): void {
  useEffect(() => {
    const prev = document.documentElement.dataset.slowcookStory;
    document.documentElement.dataset.slowcookStory = storyId;
    return () => {
      if (prev) document.documentElement.dataset.slowcookStory = prev;
      else delete document.documentElement.dataset.slowcookStory;
    };
  }, [storyId]);
}
`;
}

function personasTs(plan: LcrPlan): string {
  const personas = plan.personas.map((p) => {
    const surfaces = plan.surfaces.filter((s) => s.persona === p.id);
    const home = surfaces.find((s) => s.home)?.route ?? surfaces[0]?.route ?? "/";
    return {
      id: p.id,
      chrome: p.chrome ?? "member",
      home,
      routes: [...new Set(surfaces.map((s) => s.route))],
    };
  });
  return `// Persona registry — derived from the LCR plan by \`slowcook vibe app\`.
export interface Persona { id: string; chrome: "member" | "public" | "admin"; home: string; routes: string[] }
export const PERSONAS: Persona[] = ${j(personas, null, 2)};
`;
}

function shellTsx(): string {
  return `import { useState } from "react";
import { Link, Outlet, useLocation } from "react-router-dom";
import { PERSONAS } from "./personas";

/** The LCR shell: a chrome-aware nav for the active persona + a persona/theme
 *  switcher. Every route stays reachable (the full route list is always linked),
 *  so reviewers can navigate the whole app without auth walls. */
export function Shell() {
  const [persona, setPersona] = useState(PERSONAS[0]?.id ?? "");
  const [theme, setTheme] = useState<"dark" | "day">("dark");
  const active = PERSONAS.find((p) => p.id === persona) ?? PERSONAS[0];
  const loc = useLocation();

  function toggleTheme() {
    const next = theme === "dark" ? "day" : "dark";
    setTheme(next);
    document.documentElement.dataset.theme = next;
  }

  return (
    <div style={{ display: "flex", minHeight: "100vh" }}>
      <aside style={{ width: 248, borderRight: "1px solid var(--color-border)", padding: 16, boxSizing: "border-box" }}>
        <div style={{ fontWeight: 800, marginBottom: 12 }}>LCR · review</div>
        <label style={{ fontSize: 12, opacity: 0.7 }}>Viewing as</label>
        <select value={persona} onChange={(e) => setPersona(e.target.value)} style={{ width: "100%", margin: "6px 0 14px", padding: 6 }}>
          {PERSONAS.map((p) => (
            <option key={p.id} value={p.id}>{p.id} ({p.chrome})</option>
          ))}
        </select>
        <button onClick={toggleTheme} style={{ marginBottom: 16, padding: "4px 10px" }}>{theme === "dark" ? "☾ dark" : "☀ day"}</button>
        <nav style={{ display: "flex", flexDirection: "column", gap: 4 }}>
          <div style={{ fontSize: 11, textTransform: "uppercase", opacity: 0.6, margin: "8px 0 2px" }}>{active?.id} surfaces</div>
          {(active?.routes ?? []).map((r) => (
            <Link key={r} to={r} style={{ color: loc.pathname === r ? "var(--color-brand)" : "var(--color-text)", textDecoration: "none", padding: "2px 0" }}>{r}</Link>
          ))}
        </nav>
      </aside>
      <main style={{ flex: 1, padding: 24 }}>
        <Outlet />
      </main>
    </div>
  );
}
`;
}

function pageStub(e: RouteEntry): string {
  const story = e.stories[0] ?? "";
  return `import { useStoryMarker } from "../shell/useStoryMarker";

// @story ${e.stories.map((s) => `story-${s}`).join(", ")}
// STUB — generated by \`slowcook vibe app\`. The page body is a placeholder;
// \`slowcook vibe surfaces\` replaces it with the designed UI rendering via
// ../lib/queries. The route, persona shell, and @story marker are real.
export function ${e.component}() {
  useStoryMarker(${j(story)});
  return (
    <section>
      <h1 style={{ marginTop: 0 }}>${e.route}</h1>
      <p style={{ opacity: 0.7 }}>
        persona: ${e.personas.join(", ")} · story: ${e.stories.map((s) => `story-${s}`).join(", ")}${e.home ? " · home" : ""}
      </p>
      <p style={{ opacity: 0.7 }}>states to cover: ${e.states.length ? e.states.join(", ") : "(none declared)"}</p>
      <div style={{ marginTop: 16, padding: 16, border: "1px dashed var(--color-border)", borderRadius: 8 }}>
        ▢ page body — run <code>slowcook vibe surfaces</code> to generate the UI (renders via the SQLite data adaptor in <code>../lib/queries</code>).
      </div>
    </section>
  );
}
`;
}

function appTsx(entries: RouteEntry[]): string {
  const imports = entries.map((e) => `import { ${e.component} } from "./pages/${e.component}";`).join("\n");
  const routes = entries
    .map((e) => `        <Route path=${j(e.route)} element={<${e.component} />} />`)
    .join("\n");
  const homeRoute = entries.find((e) => e.home)?.route ?? entries[0]?.route ?? "/";
  return `import { HashRouter, Routes, Route, Navigate } from "react-router-dom";
import { Shell } from "./shell/Shell";
${imports}

// LCR app — generated by \`slowcook vibe app\`. Every declared surface is a route;
// no auth guards (barrier-free review). HashRouter keeps it static-deployable.
export function App() {
  return (
    <HashRouter>
      <Routes>
        <Route element={<Shell />}>
${routes}
          <Route path="/" element={<Navigate to=${j(homeRoute)} replace />} />
        </Route>
      </Routes>
    </HashRouter>
  );
}
`;
}

/** The `.brewing/mock.yaml` content — declares the LCR shape so run-mock + the
 *  overlay behave whole-app (device-flow auth, overlay on every route). */
export function mockYaml(): string {
  return `# Generated by \`slowcook vibe app\`. Whole-app LCR mock.
schema_version: 1
shape: vite
review_mode: lcr
mock_root: mock
design_system_dir: mock/src/design-system
screens_root: mock/src/pages
router_file: mock/src/App.tsx
`;
}

/** Build the full deterministic LCR app file set from the plan. */
export function generateLcrApp(plan: LcrPlan, opts: { projectName: string }): GenFile[] {
  const entries = routeEntries(plan);
  const files: GenFile[] = [
    { path: "package.json", content: packageJson(opts.projectName) },
    { path: "vite.config.ts", content: viteConfig() },
    { path: "index.html", content: indexHtml(opts.projectName) },
    { path: "tsconfig.json", content: tsconfig() },
    { path: "src/main.tsx", content: mainTsx() },
    { path: "src/index.css", content: indexCss() },
    { path: "src/vite-env.d.ts", content: viteEnvDts() },
    { path: "src/shell/personas.ts", content: personasTs(plan) },
    { path: "src/shell/useStoryMarker.ts", content: useStoryMarker() },
    { path: "src/shell/Shell.tsx", content: shellTsx() },
    { path: "src/App.tsx", content: appTsx(entries) },
  ];
  for (const e of entries) files.push({ path: `src/pages/${e.component}.tsx`, content: pageStub(e) });
  return files;
}
