/**
 * GUCDI — deterministic LCR app generator (pure). The final scaffolding pass of
 * the whole-app `vibe`: turns the LCR plan (routes + personas) into a RUNNABLE,
 * NAVIGABLE Vite/React app — the scaffold (package.json, vite, tailwind v4) + the
 * router (every declared surface a route, no auth walls) + a stub page per route
 * (sets the `@story` marker) — with the **slowcook review-overlay** mounted to
 * provide all REVIEW affordances (persona switch + EPSS epic·persona·scenario·state
 * router + comment capture). Personas live in the overlay's EPSS manifest, NOT in
 * the mock's chrome. No LLM: the skeleton is deterministic; the LLM `vibe surfaces`
 * pass later fills each stub's body. See docs/plans/vibe-whole-mock-lcr.md.
 */
import type { LcrPlan } from "./lcr-plan.js";

export interface GenFile {
  /** path relative to the mock root (e.g. "src/App.tsx"). */
  path: string;
  content: string;
}

/** route → React component name: "/admin/workers" → "AdminWorkersPage", "/" → "HomePage". */
export function routeToName(route: string): string {
  const pascal = (raw: string) =>
    raw
      .replace(/[^a-zA-Z0-9]+/g, " ")
      .trim()
      .split(/\s+/)
      .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : ""))
      .join("");
  // Keep param segments as `By<Param>` so `/projects/:projectId` →
  // `ProjectsByProjectIdPage`, not a meaningless `Projects2Page` collision.
  const name = route
    .split("/")
    .filter(Boolean)
    .map((s) => (s.startsWith(":") ? "By" + pascal(s.slice(1)) : pascal(s)))
    .join("");
  return (name || "Home") + "Page";
}

interface RouteEntry {
  route: string;
  component: string;
  personas: string[];
  stories: string[];
  states: string[];
  home: boolean;
}

/** Group surfaces by unique route + assign collision-free component names. */
function routeEntries(plan: LcrPlan): RouteEntry[] {
  const byRoute = new Map<string, RouteEntry>();
  for (const s of plan.surfaces) {
    let e = byRoute.get(s.route);
    if (!e) {
      e = { route: s.route, component: "", personas: [], stories: [], states: [], home: false };
      byRoute.set(s.route, e);
    }
    if (!e.personas.includes(s.persona)) e.personas.push(s.persona);
    if (!e.stories.includes(s.storyId)) e.stories.push(s.storyId);
    for (const st of s.states) if (!e.states.includes(st)) e.states.push(st);
    if (s.home) e.home = true;
  }
  const used = new Set<string>();
  for (const e of byRoute.values()) {
    let name = routeToName(e.route);
    if (used.has(name)) {
      let i = 2;
      while (used.has(`${name.replace(/Page$/, "")}${i}Page`)) i++;
      name = `${name.replace(/Page$/, "")}${i}Page`;
    }
    used.add(name);
    e.component = name;
  }
  return [...byRoute.values()];
}

const j = JSON.stringify;
/** Slug a route into an id segment for the EPSS manifest. */
function routeSlug(route: string): string {
  return route.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "").toLowerCase() || "home";
}

function packageJson(name: string): string {
  return (
    j(
      {
        name: `${name}-lcr-mock`,
        private: true,
        type: "module",
        scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
        dependencies: {
          "@slowcook-ai/review-overlay": "^0.9.0",
          react: "^19.0.0",
          "react-dom": "^19.0.0",
          "react-router-dom": "^7.0.0",
          "drizzle-orm": "^0.36.0",
          "sql.js": "^1.10.3",
        },
        devDependencies: {
          "@tailwindcss/vite": "^4.0.0",
          "@vitejs/plugin-react": "^4.3.0",
          "@types/react": "^19.0.0",
          "@types/react-dom": "^19.0.0",
          "@types/sql.js": "^1.4.9",
          tailwindcss: "^4.0.0",
          typescript: "^5.6.0",
          vite: "^6.0.0",
        },
      },
      null,
      2
    ) + "\n"
  );
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// LCR mock — generated by \`slowcook vibe app\`. sql.js is CJS, so it MUST be
// pre-bundled (\`include\`) or \`import initSqlJs from "sql.js"\` throws
// "does not provide an export" in \`vite dev\` (the HMR review deploy) — even though
// \`vite build\` works. The .wasm is imported separately via \`?url\` (a vite asset,
// unaffected). BrowserRouter needs SPA fallback — vite dev provides it by default.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  optimizeDeps: { include: ["sql.js"] },
});
`;
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name} — LCR</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function tsconfig(): string {
  return (
    j(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          module: "ESNext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          types: ["vite/client"],
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n"
  );
}

function mainTsx(): string {
  return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { App } from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
`;
}

function indexCss(): string {
  return `@import "./design-system/theme.css";

html, body, #root { height: 100%; }
body { margin: 0; background: var(--color-bg); color: var(--color-text); font-family: var(--font-sans, system-ui, sans-serif); }
`;
}

function viteEnvDts(): string {
  return `/// <reference types="vite/client" />
declare module "*?url" { const url: string; export default url; }
`;
}

function useStoryMarker(): string {
  return `import { useEffect } from "react";

/** Sets document.documentElement.dataset.slowcookStory so the review overlay can
 *  attribute LCR comments to the right story (the runtime @story marker). */
export function useStoryMarker(storyId: string): void {
  useEffect(() => {
    const prev = document.documentElement.dataset.slowcookStory;
    document.documentElement.dataset.slowcookStory = storyId;
    return () => {
      if (prev) document.documentElement.dataset.slowcookStory = prev;
      else delete document.documentElement.dataset.slowcookStory;
    };
  }, [storyId]);
}
`;
}

/** The `surfaces` prop for the overlay's "Viewing as" persona switcher — named
 *  entry points the reviewer hops between (one per persona → its home route). */
function reviewSurfacesTs(plan: LcrPlan): string {
  const surfaces = plan.personas.map((p) => {
    const ps = plan.surfaces.filter((s) => s.persona === p.id);
    const home = ps.find((s) => s.home)?.route ?? ps[0]?.route ?? "/";
    return { label: p.id, home };
  });
  return `// Review surfaces — the overlay's "Viewing as" persona switcher (review
// affordance; lives in the overlay, NOT the mock chrome). One per persona.
export const REVIEW_SURFACES = ${j(surfaces, null, 2)};
`;
}

/** The EPSS testing-surfaces.json manifest: epic ▸ context(persona) ▸ scenario
 *  (surface/route) ▸ state. The overlay renders this as the EPSS router and writes
 *  the resolved selection to localStorage for the mock's data adaptor. */
export function epssManifestJson(plan: LcrPlan, projectName: string): string {
  const contexts = plan.personas.map((p) => {
    const ps = plan.surfaces.filter((s) => s.persona === p.id);
    const home = ps.find((s) => s.home)?.route ?? ps[0]?.route ?? "/";
    // one scenario per unique route; union the declared states across surfaces.
    const statesByRoute = new Map<string, Set<string>>();
    const order: string[] = [];
    for (const s of ps) {
      if (!statesByRoute.has(s.route)) { statesByRoute.set(s.route, new Set()); order.push(s.route); }
      for (const st of s.states.length ? s.states : ["default"]) statesByRoute.get(s.route)!.add(st);
    }
    const scenarios = order.map((route) => ({
      id: routeSlug(route),
      label: route,
      route,
      states: [...statesByRoute.get(route)!].map((st) => ({ id: st, label: st })),
    }));
    return { id: p.id, label: p.id, base: home, scenarios };
  });
  const manifest = {
    activeEpicDefault: "app",
    epics: [{ id: "app", label: projectName, contexts }],
  };
  return j(manifest, null, 2) + "\n";
}

function shellTsx(): string {
  // Minimal layout. ALL review navigation (persona switch + EPSS surface/state
  // router) is provided by the overlay, not the mock chrome.
  return `import { Outlet } from "react-router-dom";

export function Shell() {
  return (
    <main style={{ minHeight: "100vh", maxWidth: 1100, margin: "0 auto", padding: 24 }}>
      <Outlet />
    </main>
  );
}
`;
}

function pageStub(e: RouteEntry): string {
  const story = e.stories[0] ?? "";
  return `import { useStoryMarker } from "../shell/useStoryMarker";

// @story ${e.stories.map((s) => `story-${s}`).join(", ")}
// STUB — generated by \`slowcook vibe app\`. The page body is a placeholder;
// \`slowcook vibe surfaces\` replaces it with the designed UI rendering via
// ../lib/queries. The route, the @story marker, and the overlay are real.
export function ${e.component}() {
  useStoryMarker(${j(story)});
  return (
    <section>
      <h1 style={{ marginTop: 0 }}>${e.route}</h1>
      <p style={{ opacity: 0.7 }}>
        persona: ${e.personas.join(", ")} · story: ${e.stories.map((s) => `story-${s}`).join(", ")}${e.home ? " · home" : ""}
      </p>
      <p style={{ opacity: 0.7 }}>states to cover: ${e.states.length ? e.states.join(", ") : "(none declared)"}</p>
      <div style={{ marginTop: 16, padding: 16, border: "1px dashed var(--color-border)", borderRadius: 8 }}>
        ▢ page body — run <code>slowcook vibe surfaces</code> to generate the UI (renders via the SQLite data adaptor in <code>../lib/queries</code>). Use the review pill (bottom) to switch persona / EPSS surface.
      </div>
    </section>
  );
}
`;
}

function appTsx(entries: RouteEntry[], owner: string, repo: string): string {
  const imports = entries.map((e) => `import { ${e.component} } from "./pages/${e.component}";`).join("\n");
  const routes = entries.map((e) => `          <Route path=${j(e.route)} element={<${e.component} />} />`).join("\n");
  const homeRoute = entries.find((e) => e.home)?.route ?? entries[0]?.route ?? "/";
  return `import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { SlowcookReviewOverlay } from "@slowcook-ai/review-overlay/react";
import { Shell } from "./shell/Shell";
import { REVIEW_SURFACES } from "./review-surfaces";
${imports}

// LCR app — generated by \`slowcook vibe app\`. Every declared surface is a route;
// no auth guards (barrier-free review). The slowcook review-overlay provides ALL
// review affordances — the "Viewing as" persona switcher (REVIEW_SURFACES) and the
// EPSS epic·persona·scenario·state router (/testing-surfaces.json) — so personas
// live in the overlay, not the mock chrome. BrowserRouter so the overlay's
// pushState navigation resolves to real routes.
export function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<Shell />}>
${routes}
          <Route path="/" element={<Navigate to=${j(homeRoute)} replace />} />
        </Route>
      </Routes>
      <SlowcookReviewOverlay
        enabled
        reviewMode="lcr"
        owner=${j(owner)}
        repo=${j(repo)}
        surfaces={REVIEW_SURFACES}
        testingSurfacesUrl="/testing-surfaces.json"
      />
    </BrowserRouter>
  );
}
`;
}

/** The `.brewing/mock.yaml` content — declares the LCR shape so run-mock + the
 *  overlay behave whole-app (device-flow auth, overlay on every route). */
export function mockYaml(): string {
  return `# Generated by \`slowcook vibe app\`. Whole-app LCR mock.
schema_version: 1
shape: vite
review_mode: lcr
mock_root: mock
design_system_dir: mock/src/design-system
screens_root: mock/src/pages
router_file: mock/src/App.tsx
`;
}

/** Build the full deterministic LCR app file set from the plan. */
export function generateLcrApp(plan: LcrPlan, opts: { projectName: string; owner?: string; repo?: string }): GenFile[] {
  const entries = routeEntries(plan);
  const owner = opts.owner ?? "";
  const repo = opts.repo ?? "";
  const files: GenFile[] = [
    { path: "package.json", content: packageJson(opts.projectName) },
    { path: "vite.config.ts", content: viteConfig() },
    { path: "index.html", content: indexHtml(opts.projectName) },
    { path: "tsconfig.json", content: tsconfig() },
    { path: "src/main.tsx", content: mainTsx() },
    { path: "src/index.css", content: indexCss() },
    { path: "src/vite-env.d.ts", content: viteEnvDts() },
    { path: "src/review-surfaces.ts", content: reviewSurfacesTs(plan) },
    { path: "src/shell/useStoryMarker.ts", content: useStoryMarker() },
    { path: "src/shell/Shell.tsx", content: shellTsx() },
    { path: "src/App.tsx", content: appTsx(entries, owner, repo) },
    { path: "public/testing-surfaces.json", content: epssManifestJson(plan, opts.projectName) },
  ];
  for (const e of entries) files.push({ path: `src/pages/${e.component}.tsx`, content: pageStub(e) });
  return files;
}
