/** CLI half of `extract --as-built` — wires the survey + dossier + LLM +
 *  citation validator together and owns process exit semantics. Kept apart
 *  from as-built.ts so the core stays pure for tests. */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { createLlmClient } from "../refine/llm.js";
import { buildDossier, generateAsBuilt, validateCitations, validateSections } from "./as-built.js";
import type { SurveyOutput } from "./survey.js";

const DEFAULT_MODEL = "claude-opus-4-8";

function walk(dir: string, root: string, acc: string[] = []): string[] {
  let entries: string[];
  try { entries = readdirSync(dir); } catch { return acc; }
  for (const name of entries) {
    if (name === "node_modules" || name === ".git" || name === "dist") continue;
    const full = join(dir, name);
    let st;
    try { st = statSync(full); } catch { continue; }
    if (st.isDirectory()) walk(full, root, acc);
    else acc.push(relative(root, full).replace(/\\/g, "/"));
  }
  return acc;
}

export async function runAsBuiltCli(
  repoRoot: string,
  survey: SurveyOutput,
  opts: { model: string | null; allowUncited: boolean },
): Promise<void> {
  let llm;
  try {
    llm = await createLlmClient();
  } catch (err) {
    console.error(`extract --as-built: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }
  const paths = walk(repoRoot, repoRoot);
  const dossier = buildDossier(repoRoot, survey, paths);
  console.log(`extract --as-built: dossier holds ${dossier.filesIncluded.length} files + survey (${survey.claims.length} claims); calling the model…`);
  const { md } = await generateAsBuilt(llm, opts.model ?? DEFAULT_MODEL, dossier);

  const missing = validateSections(md);
  if (missing.length > 0) {
    console.error(`extract --as-built: output is missing required section(s): ${missing.join(", ")} — not writing.`);
    process.exit(1);
  }
  const cites = validateCitations(md);
  if (cites.uncited.length > 0 && !opts.allowUncited) {
    console.error(`extract --as-built: ${cites.uncited.length}/${cites.bullets} bullets carry NO citation — an uncited claim is a guess. Offenders:`);
    for (const u of cites.uncited.slice(0, 10)) console.error(`  · ${u}`);
    console.error(`Re-run, or accept with --allow-uncited (the doc will keep an UNCITED marker).`);
    process.exit(1);
  }
  const banner = `> Generated by \`slowcook extract --as-built\` from ${survey.repo_head ?? "HEAD"} on ${survey.generated_at.slice(0, 10)}. Code-as-truth, as observed; regenerate when main moves.${cites.uncited.length > 0 ? ` ⚠ ${cites.uncited.length} UNCITED bullet(s) accepted via --allow-uncited.` : ""}\n\n`;
  const withBanner = md.replace(/^(# .+\n)/, `$1\n${banner}`);
  const file = join(repoRoot, ".brewing", "as-built.md");
  writeFileSync(file, withBanner, "utf8");
  console.log(`Wrote ${file} (${cites.bullets} cited bullets, ${md.split("\n## ").length - 1} sections).`);
}
